name: Deploy terraform

on:
  push:
    branches:
      - master

jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_JSON }}
        export_default_credentials: true
    - name: Install Terraform
      run: apt-get install terraform
    - name: Terraform validate
      run: sh terraform_validate.sh
    - name: Deploy GCP
      run: |
        cd terraform && terraform init && terraform apply -auto-approve -var-project_id={{secrets.PROJECT_ID}} -var-project_prefix={{secrets.PROJECT_PREFIX}} -var-service_account_email={{secrets.SERVICE_ACCOUNT}}
